### ISSUE TITLE
WebvView windows hangs on some machines. Visual Studio seems to make it work.

### ISSUE THREAD

**Issue by StevenGranados** [webview/webview_csharp#10]
On my work machine (Windows 10 Pro) everything works fine.
On my home machine (Windows 10 Home) the window was not responding and the app froze. I then took the code, built and ran it on this machine and WebView started working perfectly. It also ran fine outside of Visual Studio, and I can't get it to stop working. I tried reinstalling Visual Studio, Edge and the runtime, but it still works fine. Something about running it in VS jolted it to life. 
It also doesn't work on a colleague's PC so it's not an isolated issue to my machine.
Seems to be a couple of recent issues in the other repo.
webview/webview#491
webview/webview#490

**Comment by geaz** [comment]
Thanks for the report! I justed tested it on a fresh Win10 VM and unfortunately I was not able to reproduce the error with the 'Minimal' example. Does your colleagues PC also run Win10 Home? Did you try the 'Minimal' example or do you have an "own app" which you tested?

**Comment by StevenGranados** [comment]
Hi, thanks for the reply.
It's my own app, I start a new thread that starts the webview after the  .NET 5 app has finished starting and I ensure the webview2 runtime is installed.
His also ran Windows 10 Home, but I cant be sure it's related, because I have a lack of test PCs. I'll see if I can try the minimal example and my app in a fresh VM like you did.
I changed the thread type to STAThread after I posted this (my mistake) hoping that would solve it and the window now doesn't appear at all on his PC. I would expect the app to stop running if the webview exits, because I have it set up so that when the webview disposes the app exits.

**Comment by StevenGranados** [comment]
[TestWebWindow.zip](https://github.com/webview/webview_csharp/files/5454028/TestWebWindow.zip)
Here is a repro. It didn't work on a fresh Windows 10 VM, but did on my work PC. All of the stuff is in Startup.cs.
I published self-contained then ran the exe from the VM.

**Comment by StevenGranados** [comment]
Ah, I am trying to navigate to https://localhost:5001, but windows doesn't have a developer certificate by default. Building with VS installs the certificate and it runs. I need to navigate to http://localhost:5000. It works now.
