### ISSUE TITLE
[requirement] support Microsoft webview2 fixed version mode

### ISSUE THREAD

**Issue by congzhangzh** [webview/webview_csharp#11]
Purpose: 

    deploy .NET core webview_csharp application with self-include a fixed version WebView2 runtime.

Trouble:

    webwiew windows implement need allow to pass browserExecutableFolder to CreateCoreWebView2EnvironmentWithOptions or auto detect some default subfolder like webview2. which is not possible now. the code 
    ref:
    1. https://github.com/webview/webview/blob/master/webview.h#L871
    2. https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.622.22#createcorewebview2environmentwithoptions

Why this will extremely useful?
     
    As .NET  5 near to release,  Microsoft and .NET is cool again now, the single file release mode is cool, but once you depend webview2 runtime, you must provide an installer or depend on OS's install of Edge Browser, which is out of developer's control sometime.
     
    I think webView + asp.net Blazor will be great solution for cross platform desktop application, although Microsoft's provide their full stack to these solutions, but they seems always under refactor & reArchitecture & refusion & competition, like https://github.com/xamarin/MobileBlazorBindings, https://github.com/dotnet/maui, https://github.com/Clancey/Comet, when Microsoft find the perfect solution and implement it, the developer depends on Microsoft lost all the chance and died:)

    But we must say, some core part of Microsoft is cool, like .NET,  C#
, asp.net blazer, Edge itself, we can just mix the most reliable part of it, I have an Idea that Use WebView as asp.net Web Application container and show asp.net blazer content in it.  use webview to show the website but not the trick way of mobilebinding as that's a work in progress product( I do not know how about their relation to maui), but balzor is the core foundation part which maybe more reliable and stable.
    
ref:
1. https://github.com/webview/webview_csharp/issues/4
2. https://github.com/xamarin/MobileBlazorBindings/pull/202
3. https://github.com/MicrosoftEdge/WebView2Feedback/issues/341
4. https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#fixed-version-distribution-mode

**Comment by geaz** [comment]
Fixed Version support has to be implemented by the core webview project: https://github.com/webview/webview
Please create a feature request over there. We have to discuss the best way to integrate it to the generic api.
