### ISSUE TITLE
Only working on canary 

### ISSUE THREAD

**Issue by MitchellMonaghan** [webview/webview_csharp#12]
Hi
I'm pretty sure I tested this a few weeks ago using edge 86.0.622.51 and I thought it worked just fine. Since then I seem to only be able to get this to run on edge canary.

Currently using the newest edge Version 86.0.622.61 (Official build) (64-bit) and cant seem to get it working. It opens a window but behaves like it failed to instantiate the webview.

**Comment by geaz** [comment]
Duplication
