### ISSUE TITLE
Only working on canary

### ISSUE THREAD

**Issue by MitchellMonaghan** [webview/webview_csharp#13]
Hi
I'm pretty sure I tested this a few weeks ago using edge 86.0.622.51 and I thought it worked just fine. Since then I seem to only be able to get this to run on edge canary.

Currently using the newest edge Version 86.0.622.61 (Official build) (64-bit) and cant seem to get it working. It opens a window but behaves like it failed to instantiate the webview.

Thank your for your help and maintaining c# bindings for this.

**Comment by geaz** [comment]
Hey! If a non valid Edge Chromium version is present on the current system, webview will fallback to the old Edge. Therefore you should never get a blank window. Only difference should be the used browser engine. May I ask what you mean with "behaves like it failed to instantiate the webview"?

**Comment by MitchellMonaghan** [comment]
it opens the window, but there doesn't seem to be a webview. On right click there is no context menu, F5(refresh), F12(dev tools) seem to have no effect.

**Comment by geaz** [comment]
Could you please test, if the minimal example is working for you.

**Comment by MitchellMonaghan** [comment]
Just tested, the minimal example did work. So something else is going on. I had tried to create my own minimal example and encounter the same issue so it think its something in my project or build.

**Comment by MitchellMonaghan** [comment]
It seems to specifically break when I use http://localhost:8080

**Comment by geaz** [comment]
Please execute the following in admin command prompt and try again:

CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.Win32WebViewHost_cw5n1h2txyewy"

**Comment by MitchellMonaghan** [comment]
Still seems to be broken after running that command

**Comment by geaz** [comment]
Do you have something running on http://localhost:8080? Just changing the URL to localhost in the minimal example will not automatically host a webserver. If you want the application to host its content you have to use a HostedContent like in the DesktopApp example.

**Comment by MitchellMonaghan** [comment]
Yes I am using localhost for development to support hot reloading

**Comment by geaz** [comment]
Did you check, if the DesktopApp example works? If not, it sounds like there is still a problem with the loopback. If the above command was not working for you, you also could check the loopback settings with this gui manager: https://github.com/tiagonmas/Windows-Loopback-Exemption-Manager

**Comment by MitchellMonaghan** [comment]
Hi so I'm not sure what happened maybe I gave you false feeback. It randomly started working on my machine I'm not sure what exactly happened or when it started working. Was trying to fix this in between other work issues. 

I checked with a coworker that it was still broken on his machine, had him run your command and then it was working on his machine. So I assume running the command is what fixed it on mine but I'm not sure why it didn't work right away.

**Comment by MitchellMonaghan** [comment]
Is this something that should be documented in the readme? I assume most people will develop on localhost as they build their web ui. Thanks so much for your help investigating this with me, I really appreciate it

**Comment by MitchellMonaghan** [comment]
Also it would be nice if the window gave more feed back as to what the issue was if thats possible. Right now it just looked like it failed to create the webview.

**Comment by geaz** [comment]
No problem. The problem with the localhost is already documented in the readme. 

But yes, maybe it is possible to check, if the command ran successfully and to give feedback. Good idea! :)

**Comment by MitchellMonaghan** [comment]
Oh sorry I didn't see that section...and I read the documentation multiple times...haha

**Comment by geaz** [comment]
Implemented a check. If loopback is not enabled on windows, the library will now show a message.

![grafik](https://user-images.githubusercontent.com/1579505/98445330-71ac1700-2117-11eb-8b1b-d6596b1f3804.png)

Have to test it on linux. As soon as everything is running fine, I will release a new version including this feature.

**Comment by geaz** [comment]
Closed by #13
