### ISSUE TITLE
webview.Return fails to resolve when passed a primitive string

### ISSUE THREAD

**Issue by MitchellMonaghan** [webview/webview_csharp#14]
I'm not sure if this is intended but if you pass something like
```
webview.Return(id, RPCResult.Success, JsonConvert.SerializeObject(true));
```
OR
```
webview.Return(id, RPCResult.Success, "yup");
```

The promise hangs and is not resolved or rejected. I think either just the string should be passed as a primitive or an exception should be thrown. Right now I assume some sort of json parser is silently failing.

I have written helper functions for my self to prevent a silly error like this
```
public void ResolvePromise(string id, object data)
        {
            Webview webview = this;
            string jsonData = "{ data: " + JsonConvert.SerializeObject(data) + "}";

            webview.Return(id, RPCResult.Success, jsonData);
        }
```

**Comment by geaz** [comment]
This is more a webview issue than a binding issue. Will close it here, but feel free to open one here: https://github.com/webview/webview

That said, I will look into it :)
