### ISSUE TITLE
Right click context menu issue

### ISSUE THREAD

**Issue by MitchellMonaghan** [webview/webview_csharp#15]
If I use normal edge (Version 86.0.622.63 (Official build) (64-bit)) right clicking does not open a context menu.
If I use canary edge I can right click and use dev tools to debug js code in the webview/browser.

It would be nice to control this for production purposes, but also I'm not sure why one works and one does not. The webview takes a debug boolean but this didn't seem to have any effect on the browser context menu or dev tool access in the webview. I assume that's what the intention is tho.

https://godoc.org/github.com/zserge/webview#New

**Comment by geaz** [comment]
The chrome edge webview has a build in debugger. For the "old" one you have to use the "Microsoft Edge DevTools". You can get the app in the windows store.

**Comment by MitchellMonaghan** [comment]
Yes this is the chromium edge, and the browser/chrome dev tools are inaccessible unless using canary.
