### ISSUE TITLE
Application crash. Edge Chromium

### ISSUE THREAD

**Issue by fpetrov** [webview/webview_csharp#17]
Hello! I am using Windows 10 (19041.685) with new Edge Chromium (87.0.664.57). I have created a test project with SharpWebview but the application crashes(screenshot below). Loopback is also enabled on my machine. 
Do you have any idea how to fix this?
![Error](https://user-images.githubusercontent.com/49500051/101756841-83eaed80-3ae7-11eb-930e-7f269a403c50.png)

**Comment by geaz** [comment]
Please add [STAThread] above your Main method. Like in the example: https://github.com/webview/webview_csharp#a-basic-example

**Comment by fpetrov** [comment]
Thanks, I forgot to add this attribute, but the application still crashes with the same error. I tried to run this program on my other computer, and it works there, but I still don't understand the reason why it crashes on this computer.
![Error](https://user-images.githubusercontent.com/49500051/101765543-830b8900-3af2-11eb-9534-1bb4da5f2e78.png)
.

**Comment by geaz** [comment]
Does your other PC runs another version of Edge? I think we have to update the Webkit2 nuget for the latest edge version.

**Comment by fpetrov** [comment]
No, both computers have the same version of Edge.

**Comment by fpetrov** [comment]
I just ran the same program in Go and realized that it was using the "new" Edge, while on my main PC the program was using the "old" Edge (I figured this out from the link drag difference). I assume that because of this, the program does not run on other PCs.
