### ISSUE TITLE
Serving DLLs gives a 404

### ISSUE THREAD

**Issue by Fredolx** [webview/webview_csharp#22]
Trying to serve a Blazor WebAssembly app gives 404s when the app tries to serve DLL files

![image](https://user-images.githubusercontent.com/38048855/150804532-18ca63af-2f2c-4593-8b2d-2ef504b707fd.png)

Files of other types such as .js work correctly. Is there something that can be configured, maybe mimetypes?

**Comment by Fredolx** [comment]
https://github.com/webview/webview_csharp/pull/23

I made this PR to solve the problem

**Comment by geaz** [comment]
Fixed by PR.
