### ISSUE TITLE
Deprecated and/or vulnerable dependencies

### ISSUE THREAD

**Issue by Lemonify** [webview/webview_csharp#34]
Hello there!

There are some packages that are considered and marked as deprecated and/or vulnerable. Specifically these two:
- **Microsoft.AspNetCore.Server.IIS** (there is a newer version without vulnerabilities, but still deprecated and not being actively developed anymore)
- **Newtonsoft.Json** (based on my observations it is safe to upgrade to latest version)

However, according to official deprecation list, whole Microsoft.AspNetCore runtime is being deprecated (which makes sense, .NET Core is not supported since December 2022) and all these nugets should be natively part of the .NET 6+ if I am not mistaken. Upgrade to at least .NET 6 might be best solution.

**Comment by geaz** [comment]
Thats great! Thank you! Will check it.

**Comment by geaz** [comment]
Closed by #35
