### ISSUE TITLE
[Bug] Return from bind only supports ASCII

### ISSUE THREAD

**Issue by rthomasv3** [webview/webview_csharp#39]
If I try to return any UTF-8 or Unicode characters from a bound method, nothing is returned to the frontend.

This seems to have been resolved in webiew and will hopefully only require an update to the native assemblies.

https://github.com/webview/webview/issues/1066

**Comment by geaz** [comment]
Hey! I just build the latest dll (hope you are using windows). Could you test, if your problem is fixed with this assembly? If it is working, I will build & publish a new nuget.

[webview.zip](https://github.com/webview/webview_csharp/files/14631835/webview.zip)

**Comment by rthomasv3** [comment]
> Hey! I just build the latest dll (hope you are using windows). Could you test, if your problem is fixed with this assembly? If it is working, I will build & publish a new nuget.
> 
> [webview.zip](https://github.com/webview/webview_csharp/files/14631835/webview.zip)

Thanks for taking a look so quickly.

The updated dll is working great - I was able to return the contents of a full utf-8 encoded document back to the frontend without issue.

**Comment by rthomasv3** [comment]
@geaz Any update on this?

**Comment by geaz** [comment]
@rthomasv3 Sorry! Wanted to test it a bit and then life came along :)
Just updated the nuget to version number 0.10.0 including the new webview libraries.
