### ISSUE TITLE
Run async eval?

### ISSUE THREAD

**Issue by ilsubyeega** [webview/webview_csharp#6]
```csharp
[STAThread]
		static async void Uwu()
		{
			using (var webview = new Webview())
			{
				webview
					.SetTitle("test")
					.SetSize(1024, 768, WebviewHint.None)
					.SetSize(800, 600, WebviewHint.Min)

					.Bind("evaltest", (id, req) =>
					{
						Thread.Sleep(5000);
						Console.WriteLine(req);
						// Executes the javascript on the webview
						webview.Evaluate("console.log('The anwser is ' + window.x);");
						// And returns a successful promise result to the javascript function, which executed the 'evalTest'
						webview.Return(id, RPCResult.Success, "{ result: 'We always knew it!' }");
					})
					.Navigate(new UrlContent("http://127.0.0.1:5500/test.html"))
					.Run();
			}
		}
```

I'm trying to what features working or not.
Since it is Single Threaded, The `Thread.Sleep(5000)` will just froze the window.
how can we wait a few seconds and give result like `Thread.Sleep(5000);`?

**Comment by geaz** [comment]
At least two solutions I can think of: 
1. Use a Task inside your Bind delegate
2. Run webview in an extra thread

I would say this is more a question of your architecture then a question about what you are able to do with webview.

**Comment by ilsubyeega** [comment]
> At least two solutions I can think of:
> 
> 1. Use a Task inside your Bind delegate
> 2. Run webview in an extra thread
> 
> I would say this is more a question of your architecture then a question about what you are able to do with webview.

I selected 2, as run extra thread on bind
```csharp
.Bind("evaltest", (id, req) =>
					{
						new Thread(() =>
						{
							Thread.Sleep(5000);
							Console.WriteLine(req);
							// Executes the javascript on the webview
							webview.Evaluate("console.log('The anwser is ' + window.x);");
							// And returns a successful promise result to the javascript function, which executed the 'evalTest'
							webview.Return(id, RPCResult.Success, "{ result: 'We always knew it!' }");
						}).Start();
					})
```
whatever I used thread for just testing, I will use thread pool whatever thanks for helping me!
