### ISSUE TITLE
Is there a way to make a GTK Widget out of this library?

### ISSUE THREAD

**Issue by litch0** [webview/webview_csharp#7]

**Comment by geaz** [comment]
May I ask for the use case? If you are already using GTK, wouldn't it be easier to directly use gtk2webkit?

**Comment by litch0** [comment]
So, the thing is that I want to use the web technology (html css and js) with the Asp.Net Core Blazor to make desktop apps

**Comment by hol430** [comment]
This would also be of interest to me - the problem with gtk2webkit is that there is no windows support. It seems that the C library already pretty much does what I need(?), only problem is that the C# binding doesn't provide a public wrapper for this function:

```c
WEBVIEW_API webview_t webview_create(int debug, void *window);
```

Exposing this is as simple as adding an extra argument to the C# constructor or adding an extra constructor.

**Comment by litch0** [comment]
the problem with exposing this function is that all code envolving it must be unsafe because it returns a pointer in my understanding.

Searching a little more about the subject I found [this](https://github.com/tauri-apps/tauri/issues/1129), with a little bit of work i think it is possible, and It also uses the webview library. I plan on working on this, but not for now.
